### PR TITLE
Add validation for question pages

### LINKED ISSUE #10: Add error handling for question pages
Probably get away with not doing this but would be good to have it as close to production as possible.

### PR DESCRIPTION
**Pull request by NickColley**
This'll need a really good test since it's a lot of complexity.

Fixes https://github.com/alphagov/gaap-assistive-tech-research-prototype/issues/10

### CODE REVIEW

**Comment by hannalaakso** [comment]
I'm seeing the error summary text repeated by Mac Voiceover on Safari 13 the first time the error summary is shown (if you press submit again the message is correct). 

Screenshot 2020-02-03 at 13 46 28

**Review by 36degrees — APPROVED** [review]
Seems to work well – good stuff 👏

**Comment by NickColley** [comment]
@hannalaakso I'm using the Nunjucks patterns, can you reproduce that on govuk-frontend-review.herokuapp.com for example?

**Comment by hannalaakso** [comment]
@nickcolley No I can't reproduce it there, I'm only seeing it here. Happy to take you through it

**Comment by NickColley** [comment]
@hannalaakso yeah would be good to figure out if it's something we need to resolve for tomorrow.

**Comment by hannalaakso** [comment]
@nickcolley I've tried to reproduce it consistently but I can't. It sometimes seems to happen after clearing the user data and then going to one of the pages and submitting the form whilst not selecting anything. Having said that I haven't seen the behaviour on the review app. I think one to keep an eye out for in case someone in research uses Mac Voiceover.

**Comment by NickColley** [comment]
@hannalaakso ok, thanks a lot for the report will keep an eye out, hoping it wont be a barrier and just a minor annoyance.

**Pull request merged**
